name: Event Approve
on:
  pull_request_review:
    types: [submitted]
    branches:
      - develop

jobs:
  approved:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: |
          echo "${{github.event.pull_request.base.ref}}"
          echo "${{github.event.review.state}}"
          echo "${{github.event.pull_request.number}}"