name: Firebase Deploy Functions
on:
  push:
    branches:
      - main
jobs:
  deploy_functions:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy functions
        uses: w9jds/firebase-action@master
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATAPPTEST_EDD0D }}