name: Firebase Deploy Functions
on:
  push:
    branches:
      - main
jobs:
  deploy_functions:
    runs-on: ubuntu-lastest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Setup Firebase
        run: |
          cd ./public
          cat ls -l >> log
          cat log