name: Slack Notification
on:
  push:
    branches:
      - main

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Call Send Notification
        uses: ./call_send_notification.yml@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}