name: Slack Notification
on:
  push:
    branches:
      - main

jobs:
  send:
    uses: sarawuth-pimsai/devops/.github/workflows/call_send_notification.yml@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}