name: Slack Notification
on:
  push:
    branches:
      - feat/slacknotification

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Call Send Notification
        uses: .github/actions/call_send_notification.yml@feat/slacknotification
        with:
          token: ${{ secrets.GITHUB_TOKEN }}