name: Slack Notification
on:
  push:
    branches:
      - main

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/call_send_notification.yml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Call Send Notification
        uses: ./.github/workflows/call_send_notification.yml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}