name: Test Deploy
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Firebase
        run: npm install -g firebase-tools
      - name: Checkout Github
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: functions
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List file in functions
        run: ls -l
        working-directory: functions